# Generated by Django 4.1.7 on 2023-02-20 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_market', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='Product',
        ),
    ]
