# Generated by Django 4.1.7 on 2023-02-20 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_market', '0002_rename_products_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='picture',
            field=models.URLField(max_length=1000000, verbose_name='URL картинка'),
        ),
    ]
